# Generated by Django 2.2.3 on 2019-08-19 01:34

from django.db import migrations
import mytaggit.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaggit', '0004_auto_20181009_1248'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=mytaggit.models.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mytaggit.TaggedItem', to='mytaggit.Tag', verbose_name='Tags'),
        ),
    ]
