# Generated by Django 2.2.3 on 2019-08-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
